version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - ./server:/app 

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"   
    volumes:
      - ./client:/app  
